### ISSUE TITLE
Unable to find Docs related to Golang

### ISSUE THREAD

**Issue by tamil07** [argoproj-labs/argo-client-gen#12]
Unable to reach any of the below links.

https://github.com/argoproj/argo/blob/master/pkg/apiclient/apiclient.go
https://github.com/argoproj/argo/blob/master/cmd/argo/commands/submit.go

**Comment by alexec** [comment]
This should say `/argo-workflows/` rather than `/argo/`. Fancy submitting a pr?

**Comment by tamil07** [comment]
Sure. Created a PR for the same https://github.com/argoproj-labs/argo-client-gen/pull/13
